# Generated by Django 4.2.9 on 2024-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='opinion_admin_answer',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='visit',
            name='opinion_user',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
